language: python

sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.npm

services:
  - mysql

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
    # the Django version from requirements.txt is used
  - $DENV=""
    # the latest Django development version is used
  - $DENV="pip install --upgrade --pre Django"

# allow the Django pre version to fail without failing the entire build
matrix:
  allow_failures:
    - env: $DENV="pip install --upgrade --pre Django"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - $DENV
  - pip install coveralls
  - npm install

before_script:
# @see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - mysql -e 'CREATE DATABASE pyophase;'

# command to run tests
script:
  - export PYTHONWARNINGS=all
  - python manage.py check
    # Test against Sqlite
  - python manage.py test --exclude-tag=selenium
    # Test against MySQL
  - python manage.py test --exclude-tag=selenium --settings pyophase.settings_travis
  - coverage run --omit="*/migrations*" --source="." manage.py test --exclude-tag=selenium

after_success:
  coveralls
