language: python

dist: trusty
sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.npm

services:
  - mysql

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
    # the Django version from requirements.txt is used
  - $DENV=""
    # the latest Django development version is used
  - $DENV="pip install --upgrade --pre Django"

# allow the Django pre version to fail without failing the entire build
matrix:
  allow_failures:
    - env: $DENV="pip install --upgrade --pre Django"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - $DENV
  - pip install coveralls
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE pyophase;'

# command to run tests
script:
  - export PYTHONWARNINGS=all
  - python manage.py check
    # Test against SQLite
  - python manage.py test
    # Test against MySQL
  - python manage.py test --settings pyophase.settings_travis
  - coverage run --omit="*/migrations*" --source="." manage.py test

after_success:
  coveralls
