language: python

sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.cache/bower
  - $HOME/.npm

addons:
    code_climate:
        repo_token: 5eba139571641c629d395a5f9bec56f9cbc655ce23579c6febdede10c490c6ce

service: mysql

python:
  - "3.4"
  - "3.5"

env:
    # the Django version from requirements.txt is used
  - SQLITETEST=
    # test with mysql database
  - MYSQLTEST= DJANGO_SETTINGS_MODULE=pyophase.settings_travis
    # the latest Django development version is used
  - SQLITETEST= $DENV="pip install --upgrade --pre Django"
    # test with mysql database and the latest Django development version
  - MYSQLTEST= DJANGO_SETTINGS_MODULE=pyophase.settings_travis $DENV="pip install --upgrade --pre Django"

# allow the Django pre version to fail without failing the entire build
matrix:
  allow_failures:
    - env: $DENV="pip install --upgrade --pre Django"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - $DENV
  - pip install coveralls
  - npm install -g bower
  - bower install

before_script:
# @see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - mysql -e 'CREATE DATABASE pyophase;'

# command to run tests
script:
  - export PYTHONWARNINGS=all
  - python manage.py check 
  - python manage.py test
  - coverage run --omit="*/migrations*" --source="." manage.py test

after_success:
  coveralls
