language: python

sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.npm

services:
  - mysql

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip wheel coveralls
  - pip install -r requirements.txt
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE pyophase;'

# command to run tests
script:
  - export PYTHONWARNINGS=all
  - python manage.py check
    # Test against SQLite
  - python manage.py test
    # Test against MySQL
  - python manage.py test --settings pyophase.settings_travis
  - coverage run --omit="*/migrations*" --source="." manage.py test

after_success:
  coveralls
