# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:56
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_oinforz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='helpdesk_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
